#include "stream_core_input_enum.h"

using namespace godot;

void MoonlightInput::_bind_methods() {
	// 鼠标相关
	BIND_ENUM_CONSTANT(MOUSE_BUTTON_LEFT);
	BIND_ENUM_CONSTANT(MOUSE_BUTTON_MIDDLE);
	BIND_ENUM_CONSTANT(MOUSE_BUTTON_RIGHT);
	BIND_ENUM_CONSTANT(MOUSE_BUTTON_X1);
	BIND_ENUM_CONSTANT(MOUSE_BUTTON_X2);
	BIND_ENUM_CONSTANT(MOUSE_BUTTON_ACTION_PRESS);
	BIND_ENUM_CONSTANT(MOUSE_BUTTON_ACTION_RELEASE);

	// 键盘相关
	BIND_ENUM_CONSTANT(KEY_ACTION_DOWN_LIMIT);
	BIND_ENUM_CONSTANT(KEY_ACTION_UP_LIMIT);
	BIND_ENUM_CONSTANT(MODIFIER_NONE);
	BIND_ENUM_CONSTANT(MODIFIER_SHIFT_BIT);
	BIND_ENUM_CONSTANT(MODIFIER_CTRL_BIT);
	BIND_ENUM_CONSTANT(MODIFIER_ALT_BIT);
	BIND_ENUM_CONSTANT(MODIFIER_META_BIT);

	// 触摸与笔相关
	BIND_ENUM_CONSTANT(TOUCH_EVENT_HOVER);
	BIND_ENUM_CONSTANT(TOUCH_EVENT_DOWN);
	BIND_ENUM_CONSTANT(TOUCH_EVENT_UP);
	BIND_ENUM_CONSTANT(TOUCH_EVENT_MOVE);
	BIND_ENUM_CONSTANT(TOUCH_EVENT_CANCEL);
	BIND_ENUM_CONSTANT(TOUCH_EVENT_BUTTON_ONLY);
	BIND_ENUM_CONSTANT(TOUCH_EVENT_HOVER_LEAVE);
	BIND_ENUM_CONSTANT(TOUCH_EVENT_CANCEL_ALL);
	BIND_ENUM_CONSTANT(TOOL_TYPE_UNKNOWN);
	BIND_ENUM_CONSTANT(TOOL_TYPE_PEN);
	BIND_ENUM_CONSTANT(TOOL_TYPE_ERASER);
	BIND_ENUM_CONSTANT(PEN_BUTTON_PRIMARY);
	BIND_ENUM_CONSTANT(PEN_BUTTON_SECONDARY);
	BIND_ENUM_CONSTANT(PEN_BUTTON_TERTIARY);

	// 控制器相关
	BIND_ENUM_CONSTANT(CONTROLLER_A);
	BIND_ENUM_CONSTANT(CONTROLLER_B);
	BIND_ENUM_CONSTANT(CONTROLLER_X);
	BIND_ENUM_CONSTANT(CONTROLLER_Y);
	BIND_ENUM_CONSTANT(CONTROLLER_UP);
	BIND_ENUM_CONSTANT(CONTROLLER_DOWN);
	BIND_ENUM_CONSTANT(CONTROLLER_LEFT);
	BIND_ENUM_CONSTANT(CONTROLLER_RIGHT);
	BIND_ENUM_CONSTANT(CONTROLLER_LB);
	BIND_ENUM_CONSTANT(CONTROLLER_RB);
	BIND_ENUM_CONSTANT(CONTROLLER_PLAY);
	BIND_ENUM_CONSTANT(CONTROLLER_BACK);
	BIND_ENUM_CONSTANT(CONTROLLER_LS_CLK);
	BIND_ENUM_CONSTANT(CONTROLLER_RS_CLK);
	BIND_ENUM_CONSTANT(CONTROLLER_SPECIAL);
	BIND_ENUM_CONSTANT(CONTROLLER_PADDLE1);
	BIND_ENUM_CONSTANT(CONTROLLER_PADDLE2);
	BIND_ENUM_CONSTANT(CONTROLLER_PADDLE3);
	BIND_ENUM_CONSTANT(CONTROLLER_PADDLE4);
	BIND_ENUM_CONSTANT(CONTROLLER_TOUCHPAD);
	BIND_ENUM_CONSTANT(CONTROLLER_MISC);

	BIND_ENUM_CONSTANT(CONTROLLER_TYPE_UNKNOWN);
	BIND_ENUM_CONSTANT(CONTROLLER_TYPE_XBOX);
	BIND_ENUM_CONSTANT(CONTROLLER_TYPE_PS);
	BIND_ENUM_CONSTANT(CONTROLLER_TYPE_NINTENDO);

	BIND_ENUM_CONSTANT(CONTROLLER_CAP_ANALOG_TRIGGERS);
	BIND_ENUM_CONSTANT(CONTROLLER_CAP_RUMBLE);
	BIND_ENUM_CONSTANT(CONTROLLER_CAP_TRIGGER_RUMBLE);
	BIND_ENUM_CONSTANT(CONTROLLER_CAP_TOUCHPAD);
	BIND_ENUM_CONSTANT(CONTROLLER_CAP_ACCEL);
	BIND_ENUM_CONSTANT(CONTROLLER_CAP_GYRO);
	BIND_ENUM_CONSTANT(CONTROLLER_CAP_BATTERY_STATE);
	BIND_ENUM_CONSTANT(CONTROLLER_CAP_RGB_LED);

	// 运动与电池
	BIND_ENUM_CONSTANT(MOTION_TYPE_ACCEL);
	BIND_ENUM_CONSTANT(MOTION_TYPE_GYRO);

	BIND_ENUM_CONSTANT(BATTERY_STATE_UNKNOWN);
	BIND_ENUM_CONSTANT(BATTERY_STATE_NOT_PRESENT);
	BIND_ENUM_CONSTANT(BATTERY_STATE_DISCHARGING);
	BIND_ENUM_CONSTANT(BATTERY_STATE_CHARGING);
	BIND_ENUM_CONSTANT(BATTERY_STATE_NOT_CHARGING);
	BIND_ENUM_CONSTANT(BATTERY_STATE_FULL);

	// 特殊输入/错误常量作为枚举绑定
	BIND_ENUM_CONSTANT(INPUT_ROT_UNKNOWN);
	BIND_ENUM_CONSTANT(INPUT_TILT_UNKNOWN);
	BIND_ENUM_CONSTANT(INPUT_BATTERY_PERCENTAGE_UNKNOWN);
	BIND_ENUM_CONSTANT(INPUT_ERR_UNSUPPORTED);

	// 虚拟键码
	BIND_ENUM_CONSTANT(VK_LBUTTON);
	BIND_ENUM_CONSTANT(VK_RBUTTON);
	BIND_ENUM_CONSTANT(VK_CANCEL);
	BIND_ENUM_CONSTANT(VK_MBUTTON);
	BIND_ENUM_CONSTANT(VK_XBUTTON1);
	BIND_ENUM_CONSTANT(VK_XBUTTON2);
	BIND_ENUM_CONSTANT(VK_BACK);
	BIND_ENUM_CONSTANT(VK_TAB);
	BIND_ENUM_CONSTANT(VK_CLEAR);
	BIND_ENUM_CONSTANT(VK_RETURN);
	BIND_ENUM_CONSTANT(VK_SHIFT);
	BIND_ENUM_CONSTANT(VK_CONTROL);
	BIND_ENUM_CONSTANT(VK_MENU);
	BIND_ENUM_CONSTANT(VK_PAUSE);
	BIND_ENUM_CONSTANT(VK_CAPITAL);
	BIND_ENUM_CONSTANT(VK_KANA);
	BIND_ENUM_CONSTANT(VK_HANGUL);
	BIND_ENUM_CONSTANT(VK_IME_ON);
	BIND_ENUM_CONSTANT(VK_JUNJA);
	BIND_ENUM_CONSTANT(VK_FINAL);
	BIND_ENUM_CONSTANT(VK_HANJA);
	BIND_ENUM_CONSTANT(VK_KANJI);
	BIND_ENUM_CONSTANT(VK_IME_OFF);
	BIND_ENUM_CONSTANT(VK_ESCAPE);
	BIND_ENUM_CONSTANT(VK_CONVERT);
	BIND_ENUM_CONSTANT(VK_NONCONVERT);
	BIND_ENUM_CONSTANT(VK_ACCEPT);
	BIND_ENUM_CONSTANT(VK_MODECHANGE);
	BIND_ENUM_CONSTANT(VK_SPACE);
	BIND_ENUM_CONSTANT(VK_PRIOR);
	BIND_ENUM_CONSTANT(VK_NEXT);
	BIND_ENUM_CONSTANT(VK_END);
	BIND_ENUM_CONSTANT(VK_HOME);
	BIND_ENUM_CONSTANT(VK_LEFT);
	BIND_ENUM_CONSTANT(VK_UP);
	BIND_ENUM_CONSTANT(VK_RIGHT);
	BIND_ENUM_CONSTANT(VK_DOWN);
	BIND_ENUM_CONSTANT(VK_SELECT);
	BIND_ENUM_CONSTANT(VK_PRINT);
	BIND_ENUM_CONSTANT(VK_EXECUTE);
	BIND_ENUM_CONSTANT(VK_SNAPSHOT);
	BIND_ENUM_CONSTANT(VK_INSERT);
	BIND_ENUM_CONSTANT(VK_DELETE);
	BIND_ENUM_CONSTANT(VK_HELP);
	BIND_ENUM_CONSTANT(VK_0);
	BIND_ENUM_CONSTANT(VK_1);
	BIND_ENUM_CONSTANT(VK_2);
	BIND_ENUM_CONSTANT(VK_3);
	BIND_ENUM_CONSTANT(VK_4);
	BIND_ENUM_CONSTANT(VK_5);
	BIND_ENUM_CONSTANT(VK_6);
	BIND_ENUM_CONSTANT(VK_7);
	BIND_ENUM_CONSTANT(VK_8);
	BIND_ENUM_CONSTANT(VK_9);
	BIND_ENUM_CONSTANT(VK_A);
	BIND_ENUM_CONSTANT(VK_B);
	BIND_ENUM_CONSTANT(VK_C);
	BIND_ENUM_CONSTANT(VK_D);
	BIND_ENUM_CONSTANT(VK_E);
	BIND_ENUM_CONSTANT(VK_F);
	BIND_ENUM_CONSTANT(VK_G);
	BIND_ENUM_CONSTANT(VK_H);
	BIND_ENUM_CONSTANT(VK_I);
	BIND_ENUM_CONSTANT(VK_J);
	BIND_ENUM_CONSTANT(VK_K);
	BIND_ENUM_CONSTANT(VK_L);
	BIND_ENUM_CONSTANT(VK_M);
	BIND_ENUM_CONSTANT(VK_N);
	BIND_ENUM_CONSTANT(VK_O);
	BIND_ENUM_CONSTANT(VK_P);
	BIND_ENUM_CONSTANT(VK_Q);
	BIND_ENUM_CONSTANT(VK_R);
	BIND_ENUM_CONSTANT(VK_S);
	BIND_ENUM_CONSTANT(VK_T);
	BIND_ENUM_CONSTANT(VK_U);
	BIND_ENUM_CONSTANT(VK_V);
	BIND_ENUM_CONSTANT(VK_W);
	BIND_ENUM_CONSTANT(VK_X);
	BIND_ENUM_CONSTANT(VK_Y);
	BIND_ENUM_CONSTANT(VK_Z);
	BIND_ENUM_CONSTANT(VK_LWIN);
	BIND_ENUM_CONSTANT(VK_RWIN);
	BIND_ENUM_CONSTANT(VK_APPS);
	BIND_ENUM_CONSTANT(VK_SLEEP);
	BIND_ENUM_CONSTANT(VK_NUMPAD0);
	BIND_ENUM_CONSTANT(VK_NUMPAD1);
	BIND_ENUM_CONSTANT(VK_NUMPAD2);
	BIND_ENUM_CONSTANT(VK_NUMPAD3);
	BIND_ENUM_CONSTANT(VK_NUMPAD4);
	BIND_ENUM_CONSTANT(VK_NUMPAD5);
	BIND_ENUM_CONSTANT(VK_NUMPAD6);
	BIND_ENUM_CONSTANT(VK_NUMPAD7);
	BIND_ENUM_CONSTANT(VK_NUMPAD8);
	BIND_ENUM_CONSTANT(VK_NUMPAD9);
	BIND_ENUM_CONSTANT(VK_MULTIPLY);
	BIND_ENUM_CONSTANT(VK_ADD);
	BIND_ENUM_CONSTANT(VK_SEPARATOR);
	BIND_ENUM_CONSTANT(VK_SUBTRACT);
	BIND_ENUM_CONSTANT(VK_DECIMAL);
	BIND_ENUM_CONSTANT(VK_DIVIDE);
	BIND_ENUM_CONSTANT(VK_F1);
	BIND_ENUM_CONSTANT(VK_F2);
	BIND_ENUM_CONSTANT(VK_F3);
	BIND_ENUM_CONSTANT(VK_F4);
	BIND_ENUM_CONSTANT(VK_F5);
	BIND_ENUM_CONSTANT(VK_F6);
	BIND_ENUM_CONSTANT(VK_F7);
	BIND_ENUM_CONSTANT(VK_F8);
	BIND_ENUM_CONSTANT(VK_F9);
	BIND_ENUM_CONSTANT(VK_F10);
	BIND_ENUM_CONSTANT(VK_F11);
	BIND_ENUM_CONSTANT(VK_F12);
	BIND_ENUM_CONSTANT(VK_F13);
	BIND_ENUM_CONSTANT(VK_F14);
	BIND_ENUM_CONSTANT(VK_F15);
	BIND_ENUM_CONSTANT(VK_F16);
	BIND_ENUM_CONSTANT(VK_F17);
	BIND_ENUM_CONSTANT(VK_F18);
	BIND_ENUM_CONSTANT(VK_F19);
	BIND_ENUM_CONSTANT(VK_F20);
	BIND_ENUM_CONSTANT(VK_F21);
	BIND_ENUM_CONSTANT(VK_F22);
	BIND_ENUM_CONSTANT(VK_F23);
	BIND_ENUM_CONSTANT(VK_F24);
	BIND_ENUM_CONSTANT(VK_NUMLOCK);
	BIND_ENUM_CONSTANT(VK_SCROLL);
	BIND_ENUM_CONSTANT(VK_LSHIFT);
	BIND_ENUM_CONSTANT(VK_RSHIFT);
	BIND_ENUM_CONSTANT(VK_LCONTROL);
	BIND_ENUM_CONSTANT(VK_RCONTROL);
	BIND_ENUM_CONSTANT(VK_LMENU);
	BIND_ENUM_CONSTANT(VK_RMENU);
	BIND_ENUM_CONSTANT(VK_BROWSER_BACK);
	BIND_ENUM_CONSTANT(VK_BROWSER_FORWARD);
	BIND_ENUM_CONSTANT(VK_BROWSER_REFRESH);
	BIND_ENUM_CONSTANT(VK_BROWSER_STOP);
	BIND_ENUM_CONSTANT(VK_BROWSER_SEARCH);
	BIND_ENUM_CONSTANT(VK_BROWSER_FAVORITES);
	BIND_ENUM_CONSTANT(VK_BROWSER_HOME);
	BIND_ENUM_CONSTANT(VK_VOLUME_MUTE);
	BIND_ENUM_CONSTANT(VK_VOLUME_DOWN);
	BIND_ENUM_CONSTANT(VK_VOLUME_UP);
	BIND_ENUM_CONSTANT(VK_MEDIA_NEXT_TRACK);
	BIND_ENUM_CONSTANT(VK_MEDIA_PREV_TRACK);
	BIND_ENUM_CONSTANT(VK_MEDIA_STOP);
	BIND_ENUM_CONSTANT(VK_MEDIA_PLAY_PAUSE);
	BIND_ENUM_CONSTANT(VK_LAUNCH_MAIL);
	BIND_ENUM_CONSTANT(VK_LAUNCH_MEDIA_SELECT);
	BIND_ENUM_CONSTANT(VK_LAUNCH_APP1);
	BIND_ENUM_CONSTANT(VK_LAUNCH_APP2);
	BIND_ENUM_CONSTANT(VK_OEM_1);
	BIND_ENUM_CONSTANT(VK_OEM_PLUS);
	BIND_ENUM_CONSTANT(VK_OEM_COMMA);
	BIND_ENUM_CONSTANT(VK_OEM_MINUS);
	BIND_ENUM_CONSTANT(VK_OEM_PERIOD);
	BIND_ENUM_CONSTANT(VK_OEM_2);
	BIND_ENUM_CONSTANT(VK_OEM_3);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_A);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_B);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_X);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_Y);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_RIGHT_SHOULDER);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_LEFT_SHOULDER);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_LEFT_TRIGGER);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_RIGHT_TRIGGER);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_DPAD_UP);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_DPAD_DOWN);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_DPAD_LEFT);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_DPAD_RIGHT);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_MENU);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_VIEW);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_LEFT_THUMBSTICK_UP);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_LEFT_THUMBSTICK_DOWN);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_LEFT_THUMBSTICK_LEFT);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_RIGHT_THUMBSTICK_UP);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT);
	BIND_ENUM_CONSTANT(VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT);
	BIND_ENUM_CONSTANT(VK_OEM_4);
	BIND_ENUM_CONSTANT(VK_OEM_5);
	BIND_ENUM_CONSTANT(VK_OEM_6);
	BIND_ENUM_CONSTANT(VK_OEM_7);
	BIND_ENUM_CONSTANT(VK_OEM_8);
	BIND_ENUM_CONSTANT(VK_OEM_102);
	BIND_ENUM_CONSTANT(VK_PROCESSKEY);
	BIND_ENUM_CONSTANT(VK_PACKET);
	BIND_ENUM_CONSTANT(VK_ATTN);
	BIND_ENUM_CONSTANT(VK_CRSEL);
	BIND_ENUM_CONSTANT(VK_EXSEL);
	BIND_ENUM_CONSTANT(VK_EREOF);
	BIND_ENUM_CONSTANT(VK_PLAY);
	BIND_ENUM_CONSTANT(VK_ZOOM);
	BIND_ENUM_CONSTANT(VK_NONAME);
	BIND_ENUM_CONSTANT(VK_PA1);
	BIND_ENUM_CONSTANT(VK_OEM_CLEAR);

	// 绑定静态方法以便 GDScript 调用：将 Godot 键码转换为 Win32 虚拟键码
	ClassDB::bind_static_method("MoonlightInput",
			D_METHOD("godot_to_virtual_key", "godot_key"),
			&MoonlightInput::godot_to_virtual_key);
}

int MoonlightInput::godot_to_virtual_key(int godot_key) {
	// 常见 ASCII 字母与数字直接映射到对应的 VK_* 值
	if (godot_key >= 65 && godot_key <= 90) { // A-Z
		return godot_key; // VK_A..VK_Z == 0x41..0x5A
	}
	if (godot_key >= 48 && godot_key <= 57) { // 0-9
		return godot_key; // VK_0..VK_9 == 0x30..0x39
	}

	switch (godot_key) {
		case 32:
			return VK_SPACE;
		case 33:
			return VK_1; // '!' -> 1 + Shift
		case 34:
			return VK_OEM_7; // '"'
		case 35:
			return VK_OEM_3; // '#'
		case 36:
			return VK_OEM_4; // '$' (approx)
		case 37:
			return VK_OEM_5; // '%'
		case 38:
			return VK_7; // '&' -> 7 + Shift
		case 39:
			return VK_OEM_7; // '\''
		case 40:
			return VK_9; // '('
		case 41:
			return VK_0; // ')'
		case 42:
			return VK_MULTIPLY; // '*'
		case 43:
			return VK_OEM_PLUS; // '+'
		case 44:
			return VK_OEM_COMMA; // ','
		case 45:
			return VK_OEM_MINUS; // '-'
		case 46:
			return VK_OEM_PERIOD; // '.'
		case 47:
			return VK_OEM_2; // '/'

		// Godot 的高位特殊键（多数从 4194304 起）
		case 4194305:
			return VK_ESCAPE; // KEY_ESCAPE
		case 4194306:
			return VK_TAB; // KEY_TAB
		case 4194307:
			return VK_TAB; // KEY_BACKTAB -> treat as TAB
		case 4194308:
			return VK_BACK; // KEY_BACKSPACE
		case 4194309:
			return VK_RETURN; // KEY_ENTER
		case 4194310:
			return VK_RETURN; // KEY_KP_ENTER
		case 4194311:
			return VK_INSERT; // KEY_INSERT
		case 4194312:
			return VK_DELETE; // KEY_DELETE
		case 4194313:
			return VK_PAUSE; // KEY_PAUSE
		case 4194314:
			return VK_SNAPSHOT; // KEY_PRINT
		case 4194316:
			return VK_CLEAR; // KEY_CLEAR
		case 4194317:
			return VK_HOME; // KEY_HOME
		case 4194318:
			return VK_END; // KEY_END
		case 4194319:
			return VK_LEFT; // KEY_LEFT
		case 4194320:
			return VK_UP; // KEY_UP
		case 4194321:
			return VK_RIGHT; // KEY_RIGHT
		case 4194322:
			return VK_DOWN; // KEY_DOWN
		case 4194323:
			return VK_PRIOR; // KEY_PAGEUP
		case 4194324:
			return VK_NEXT; // KEY_PAGEDOWN

		case 4194325:
			return VK_SHIFT; // KEY_SHIFT
		case 4194326:
			return VK_CONTROL; // KEY_CTRL
		case 4194327:
			return VK_LWIN; // KEY_META -> map to LWIN
		case 4194328:
			return VK_MENU; // KEY_ALT
		case 4194329:
			return VK_CAPITAL; // KEY_CAPSLOCK
		case 4194330:
			return VK_NUMLOCK; // KEY_NUMLOCK
		case 4194331:
			return VK_SCROLL; // KEY_SCROLLLOCK

		// Function keys（Windows 支持到 F24）
		case 4194332:
			return VK_F1;
		case 4194333:
			return VK_F2;
		case 4194334:
			return VK_F3;
		case 4194335:
			return VK_F4;
		case 4194336:
			return VK_F5;
		case 4194337:
			return VK_F6;
		case 4194338:
			return VK_F7;
		case 4194339:
			return VK_F8;
		case 4194340:
			return VK_F9;
		case 4194341:
			return VK_F10;
		case 4194342:
			return VK_F11;
		case 4194343:
			return VK_F12;
		case 4194344:
			return VK_F13;
		case 4194345:
			return VK_F14;
		case 4194346:
			return VK_F15;
		case 4194347:
			return VK_F16;
		case 4194348:
			return VK_F17;
		case 4194349:
			return VK_F18;
		case 4194350:
			return VK_F19;
		case 4194351:
			return VK_F20;
		case 4194352:
			return VK_F21;
		case 4194353:
			return VK_F22;
		case 4194354:
			return VK_F23;
		case 4194355:
			return VK_F24;

		// Numpad keys
		case 4194433:
			return VK_MULTIPLY; // KEY_KP_MULTIPLY
		case 4194434:
			return VK_DIVIDE; // KEY_KP_DIVIDE
		case 4194435:
			return VK_SUBTRACT; // KEY_KP_SUBTRACT
		case 4194436:
			return VK_DECIMAL; // KEY_KP_PERIOD
		case 4194437:
			return VK_ADD; // KEY_KP_ADD
		case 4194438:
			return VK_NUMPAD0; // KEY_KP_0
		case 4194439:
			return VK_NUMPAD1; // KEY_KP_1
		case 4194440:
			return VK_NUMPAD2; // KEY_KP_2
		case 4194441:
			return VK_NUMPAD3; // KEY_KP_3
		case 4194442:
			return VK_NUMPAD4; // KEY_KP_4
		case 4194443:
			return VK_NUMPAD5; // KEY_KP_5
		case 4194444:
			return VK_NUMPAD6; // KEY_KP_6
		case 4194445:
			return VK_NUMPAD7; // KEY_KP_7
		case 4194446:
			return VK_NUMPAD8; // KEY_KP_8
		case 4194447:
			return VK_NUMPAD9; // KEY_KP_9

		// 媒体 / 启动键（常见映射）
		case 4194380:
			return VK_VOLUME_DOWN;
		case 4194381:
			return VK_VOLUME_MUTE;
		case 4194382:
			return VK_VOLUME_UP;
		case 4194388:
			return VK_MEDIA_PLAY_PAUSE;
		case 4194389:
			return VK_MEDIA_STOP;
		case 4194390:
			return VK_MEDIA_PREV_TRACK;
		case 4194391:
			return VK_MEDIA_NEXT_TRACK;
		case 4194392:
			return VK_MEDIA_STOP; // MEDIARECORD -> map to stop

		default:
			return 0; // 未知或未映射
	}
}
