#pragma once

#include "Limelight.h"
#include <godot_cpp/classes/resource.hpp>
#include <godot_cpp/core/class_db.hpp>

namespace godot {

class MoonlightInput : public Resource {
	GDCLASS(MoonlightInput, Resource);

protected:
	static void _bind_methods();

public:
	MoonlightInput() {}
	~MoonlightInput() {}

	enum MouseButton {
		MOUSE_BUTTON_LEFT = BUTTON_LEFT,
		MOUSE_BUTTON_MIDDLE = BUTTON_MIDDLE,
		MOUSE_BUTTON_RIGHT = BUTTON_RIGHT,
		MOUSE_BUTTON_X1 = BUTTON_X1,
		MOUSE_BUTTON_X2 = BUTTON_X2
	};

	enum MouseButtonAction {
		MOUSE_BUTTON_ACTION_PRESS = BUTTON_ACTION_PRESS,
		MOUSE_BUTTON_ACTION_RELEASE = BUTTON_ACTION_RELEASE
	};

	enum KeyboardAction {
		KEY_ACTION_DOWN_LIMIT = KEY_ACTION_DOWN,
		KEY_ACTION_UP_LIMIT = KEY_ACTION_UP
	};

	enum KeyboardModifier {
		MODIFIER_NONE = 0,
		MODIFIER_SHIFT_BIT = MODIFIER_SHIFT,
		MODIFIER_CTRL_BIT = MODIFIER_CTRL,
		MODIFIER_ALT_BIT = MODIFIER_ALT,
		MODIFIER_META_BIT = MODIFIER_META
	};

	enum TouchEventType {
		TOUCH_EVENT_HOVER = LI_TOUCH_EVENT_HOVER,
		TOUCH_EVENT_DOWN = LI_TOUCH_EVENT_DOWN,
		TOUCH_EVENT_UP = LI_TOUCH_EVENT_UP,
		TOUCH_EVENT_MOVE = LI_TOUCH_EVENT_MOVE,
		TOUCH_EVENT_CANCEL = LI_TOUCH_EVENT_CANCEL,
		TOUCH_EVENT_BUTTON_ONLY = LI_TOUCH_EVENT_BUTTON_ONLY,
		TOUCH_EVENT_HOVER_LEAVE = LI_TOUCH_EVENT_HOVER_LEAVE,
		TOUCH_EVENT_CANCEL_ALL = LI_TOUCH_EVENT_CANCEL_ALL
	};

	enum PenToolType {
		TOOL_TYPE_UNKNOWN = LI_TOOL_TYPE_UNKNOWN,
		TOOL_TYPE_PEN = LI_TOOL_TYPE_PEN,
		TOOL_TYPE_ERASER = LI_TOOL_TYPE_ERASER
	};

	enum PenButton {
		PEN_BUTTON_PRIMARY = LI_PEN_BUTTON_PRIMARY,
		PEN_BUTTON_SECONDARY = LI_PEN_BUTTON_SECONDARY,
		PEN_BUTTON_TERTIARY = LI_PEN_BUTTON_TERTIARY
	};

	enum ControllerButton {
		CONTROLLER_A = A_FLAG,
		CONTROLLER_B = B_FLAG,
		CONTROLLER_X = X_FLAG,
		CONTROLLER_Y = Y_FLAG,
		CONTROLLER_UP = UP_FLAG,
		CONTROLLER_DOWN = DOWN_FLAG,
		CONTROLLER_LEFT = LEFT_FLAG,
		CONTROLLER_RIGHT = RIGHT_FLAG,
		CONTROLLER_LB = LB_FLAG,
		CONTROLLER_RB = RB_FLAG,
		CONTROLLER_PLAY = PLAY_FLAG,
		CONTROLLER_BACK = BACK_FLAG,
		CONTROLLER_LS_CLK = LS_CLK_FLAG,
		CONTROLLER_RS_CLK = RS_CLK_FLAG,
		CONTROLLER_SPECIAL = SPECIAL_FLAG,
		CONTROLLER_PADDLE1 = PADDLE1_FLAG,
		CONTROLLER_PADDLE2 = PADDLE2_FLAG,
		CONTROLLER_PADDLE3 = PADDLE3_FLAG,
		CONTROLLER_PADDLE4 = PADDLE4_FLAG,
		CONTROLLER_TOUCHPAD = TOUCHPAD_FLAG,
		CONTROLLER_MISC = MISC_FLAG
	};

	enum ControllerType {
		CONTROLLER_TYPE_UNKNOWN = LI_CTYPE_UNKNOWN,
		CONTROLLER_TYPE_XBOX = LI_CTYPE_XBOX,
		CONTROLLER_TYPE_PS = LI_CTYPE_PS,
		CONTROLLER_TYPE_NINTENDO = LI_CTYPE_NINTENDO
	};

	enum ControllerCapability {
		CONTROLLER_CAP_ANALOG_TRIGGERS = LI_CCAP_ANALOG_TRIGGERS,
		CONTROLLER_CAP_RUMBLE = LI_CCAP_RUMBLE,
		CONTROLLER_CAP_TRIGGER_RUMBLE = LI_CCAP_TRIGGER_RUMBLE,
		CONTROLLER_CAP_TOUCHPAD = LI_CCAP_TOUCHPAD,
		CONTROLLER_CAP_ACCEL = LI_CCAP_ACCEL,
		CONTROLLER_CAP_GYRO = LI_CCAP_GYRO,
		CONTROLLER_CAP_BATTERY_STATE = LI_CCAP_BATTERY_STATE,
		CONTROLLER_CAP_RGB_LED = LI_CCAP_RGB_LED
	};

	enum MotionType {
		MOTION_TYPE_ACCEL = LI_MOTION_TYPE_ACCEL,
		MOTION_TYPE_GYRO = LI_MOTION_TYPE_GYRO
	};

	enum BatteryState {
		BATTERY_STATE_UNKNOWN = LI_BATTERY_STATE_UNKNOWN,
		BATTERY_STATE_NOT_PRESENT = LI_BATTERY_STATE_NOT_PRESENT,
		BATTERY_STATE_DISCHARGING = LI_BATTERY_STATE_DISCHARGING,
		BATTERY_STATE_CHARGING = LI_BATTERY_STATE_CHARGING,
		BATTERY_STATE_NOT_CHARGING = LI_BATTERY_STATE_NOT_CHARGING,
		BATTERY_STATE_FULL = LI_BATTERY_STATE_FULL
	};

	enum InputSpecialConstant {
		INPUT_ROT_UNKNOWN = LI_ROT_UNKNOWN,
		INPUT_TILT_UNKNOWN = LI_TILT_UNKNOWN,
		INPUT_BATTERY_PERCENTAGE_UNKNOWN = LI_BATTERY_PERCENTAGE_UNKNOWN,
		INPUT_ERR_UNSUPPORTED = LI_ERR_UNSUPPORTED
	};

#ifdef _WIN32
#undef VK_LBUTTON
#undef VK_RBUTTON
#undef VK_CANCEL
#undef VK_MBUTTON
#undef VK_XBUTTON1
#undef VK_XBUTTON2
#undef VK_BACK
#undef VK_TAB
#undef VK_CLEAR
#undef VK_RETURN
#undef VK_SHIFT
#undef VK_CONTROL
#undef VK_MENU
#undef VK_PAUSE
#undef VK_CAPITAL
#undef VK_KANA
#undef VK_HANGUL
#undef VK_IME_ON
#undef VK_JUNJA
#undef VK_FINAL
#undef VK_HANJA
#undef VK_KANJI
#undef VK_IME_OFF
#undef VK_ESCAPE
#undef VK_CONVERT
#undef VK_NONCONVERT
#undef VK_ACCEPT
#undef VK_MODECHANGE
#undef VK_SPACE
#undef VK_PRIOR
#undef VK_NEXT
#undef VK_END
#undef VK_HOME
#undef VK_LEFT
#undef VK_UP
#undef VK_RIGHT
#undef VK_DOWN
#undef VK_SELECT
#undef VK_PRINT
#undef VK_EXECUTE
#undef VK_SNAPSHOT
#undef VK_INSERT
#undef VK_DELETE
#undef VK_HELP
#undef VK_0
#undef VK_1
#undef VK_2
#undef VK_3
#undef VK_4
#undef VK_5
#undef VK_6
#undef VK_7
#undef VK_8
#undef VK_9
#undef VK_A
#undef VK_B
#undef VK_C
#undef VK_D
#undef VK_E
#undef VK_F
#undef VK_G
#undef VK_H
#undef VK_I
#undef VK_J
#undef VK_K
#undef VK_L
#undef VK_M
#undef VK_N
#undef VK_O
#undef VK_P
#undef VK_Q
#undef VK_R
#undef VK_S
#undef VK_T
#undef VK_U
#undef VK_V
#undef VK_W
#undef VK_X
#undef VK_Y
#undef VK_Z
#undef VK_LWIN
#undef VK_RWIN
#undef VK_APPS
#undef VK_SLEEP
#undef VK_NUMPAD0
#undef VK_NUMPAD1
#undef VK_NUMPAD2
#undef VK_NUMPAD3
#undef VK_NUMPAD4
#undef VK_NUMPAD5
#undef VK_NUMPAD6
#undef VK_NUMPAD7
#undef VK_NUMPAD8
#undef VK_NUMPAD9
#undef VK_MULTIPLY
#undef VK_ADD
#undef VK_SEPARATOR
#undef VK_SUBTRACT
#undef VK_DECIMAL
#undef VK_DIVIDE
#undef VK_F1
#undef VK_F2
#undef VK_F3
#undef VK_F4
#undef VK_F5
#undef VK_F6
#undef VK_F7
#undef VK_F8
#undef VK_F9
#undef VK_F10
#undef VK_F11
#undef VK_F12
#undef VK_F13
#undef VK_F14
#undef VK_F15
#undef VK_F16
#undef VK_F17
#undef VK_F18
#undef VK_F19
#undef VK_F20
#undef VK_F21
#undef VK_F22
#undef VK_F23
#undef VK_F24
#undef VK_NUMLOCK
#undef VK_SCROLL
#undef VK_LSHIFT
#undef VK_RSHIFT
#undef VK_LCONTROL
#undef VK_RCONTROL
#undef VK_LMENU
#undef VK_RMENU
#undef VK_BROWSER_BACK
#undef VK_BROWSER_FORWARD
#undef VK_BROWSER_REFRESH
#undef VK_BROWSER_STOP
#undef VK_BROWSER_SEARCH
#undef VK_BROWSER_FAVORITES
#undef VK_BROWSER_HOME
#undef VK_VOLUME_MUTE
#undef VK_VOLUME_DOWN
#undef VK_VOLUME_UP
#undef VK_MEDIA_NEXT_TRACK
#undef VK_MEDIA_PREV_TRACK
#undef VK_MEDIA_STOP
#undef VK_MEDIA_PLAY_PAUSE
#undef VK_LAUNCH_MAIL
#undef VK_LAUNCH_MEDIA_SELECT
#undef VK_LAUNCH_APP1
#undef VK_LAUNCH_APP2
#undef VK_OEM_1
#undef VK_OEM_PLUS
#undef VK_OEM_COMMA
#undef VK_OEM_MINUS
#undef VK_OEM_PERIOD
#undef VK_OEM_2
#undef VK_OEM_3
#undef VK_GAMEPAD_A
#undef VK_GAMEPAD_B
#undef VK_GAMEPAD_X
#undef VK_GAMEPAD_Y
#undef VK_GAMEPAD_RIGHT_SHOULDER
#undef VK_GAMEPAD_LEFT_SHOULDER
#undef VK_GAMEPAD_LEFT_TRIGGER
#undef VK_GAMEPAD_RIGHT_TRIGGER
#undef VK_GAMEPAD_DPAD_UP
#undef VK_GAMEPAD_DPAD_DOWN
#undef VK_GAMEPAD_DPAD_LEFT
#undef VK_GAMEPAD_DPAD_RIGHT
#undef VK_GAMEPAD_MENU
#undef VK_GAMEPAD_VIEW
#undef VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON
#undef VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON
#undef VK_GAMEPAD_LEFT_THUMBSTICK_UP
#undef VK_GAMEPAD_LEFT_THUMBSTICK_DOWN
#undef VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT
#undef VK_GAMEPAD_LEFT_THUMBSTICK_LEFT
#undef VK_GAMEPAD_RIGHT_THUMBSTICK_UP
#undef VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN
#undef VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT
#undef VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT
#undef VK_OEM_4
#undef VK_OEM_5
#undef VK_OEM_6
#undef VK_OEM_7
#undef VK_OEM_8
#undef VK_OEM_102
#undef VK_PROCESSKEY
#undef VK_PACKET
#undef VK_ATTN
#undef VK_CRSEL
#undef VK_EXSEL
#undef VK_EREOF
#undef VK_PLAY
#undef VK_ZOOM
#undef VK_NONAME
#undef VK_PA1
#undef VK_OEM_CLEAR
#endif

	enum VirtualKey {
		VK_LBUTTON = 0x01,
		VK_RBUTTON = 0x02,
		VK_CANCEL = 0x03,
		VK_MBUTTON = 0x04,
		VK_XBUTTON1 = 0x05,
		VK_XBUTTON2 = 0x06,
		VK_BACK = 0x08,
		VK_TAB = 0x09,
		VK_CLEAR = 0x0C,
		VK_RETURN = 0x0D,
		VK_SHIFT = 0x10,
		VK_CONTROL = 0x11,
		VK_MENU = 0x12,
		VK_PAUSE = 0x13,
		VK_CAPITAL = 0x14,
		VK_KANA = 0x15,
		VK_HANGUL = 0x15,
		VK_IME_ON = 0x16,
		VK_JUNJA = 0x17,
		VK_FINAL = 0x18,
		VK_HANJA = 0x19,
		VK_KANJI = 0x19,
		VK_IME_OFF = 0x1A,
		VK_ESCAPE = 0x1B,
		VK_CONVERT = 0x1C,
		VK_NONCONVERT = 0x1D,
		VK_ACCEPT = 0x1E,
		VK_MODECHANGE = 0x1F,
		VK_SPACE = 0x20,
		VK_PRIOR = 0x21,
		VK_NEXT = 0x22,
		VK_END = 0x23,
		VK_HOME = 0x24,
		VK_LEFT = 0x25,
		VK_UP = 0x26,
		VK_RIGHT = 0x27,
		VK_DOWN = 0x28,
		VK_SELECT = 0x29,
		VK_PRINT = 0x2A,
		VK_EXECUTE = 0x2B,
		VK_SNAPSHOT = 0x2C,
		VK_INSERT = 0x2D,
		VK_DELETE = 0x2E,
		VK_HELP = 0x2F,
		VK_0 = 0x30,
		VK_1 = 0x31,
		VK_2 = 0x32,
		VK_3 = 0x33,
		VK_4 = 0x34,
		VK_5 = 0x35,
		VK_6 = 0x36,
		VK_7 = 0x37,
		VK_8 = 0x38,
		VK_9 = 0x39,
		VK_A = 0x41,
		VK_B = 0x42,
		VK_C = 0x43,
		VK_D = 0x44,
		VK_E = 0x45,
		VK_F = 0x46,
		VK_G = 0x47,
		VK_H = 0x48,
		VK_I = 0x49,
		VK_J = 0x4A,
		VK_K = 0x4B,
		VK_L = 0x4C,
		VK_M = 0x4D,
		VK_N = 0x4E,
		VK_O = 0x4F,
		VK_P = 0x50,
		VK_Q = 0x51,
		VK_R = 0x52,
		VK_S = 0x53,
		VK_T = 0x54,
		VK_U = 0x55,
		VK_V = 0x56,
		VK_W = 0x57,
		VK_X = 0x58,
		VK_Y = 0x59,
		VK_Z = 0x5A,
		VK_LWIN = 0x5B,
		VK_RWIN = 0x5C,
		VK_APPS = 0x5D,
		VK_SLEEP = 0x5F,
		VK_NUMPAD0 = 0x60,
		VK_NUMPAD1 = 0x61,
		VK_NUMPAD2 = 0x62,
		VK_NUMPAD3 = 0x63,
		VK_NUMPAD4 = 0x64,
		VK_NUMPAD5 = 0x65,
		VK_NUMPAD6 = 0x66,
		VK_NUMPAD7 = 0x67,
		VK_NUMPAD8 = 0x68,
		VK_NUMPAD9 = 0x69,
		VK_MULTIPLY = 0x6A,
		VK_ADD = 0x6B,
		VK_SEPARATOR = 0x6C,
		VK_SUBTRACT = 0x6D,
		VK_DECIMAL = 0x6E,
		VK_DIVIDE = 0x6F,
		VK_F1 = 0x70,
		VK_F2 = 0x71,
		VK_F3 = 0x72,
		VK_F4 = 0x73,
		VK_F5 = 0x74,
		VK_F6 = 0x75,
		VK_F7 = 0x76,
		VK_F8 = 0x77,
		VK_F9 = 0x78,
		VK_F10 = 0x79,
		VK_F11 = 0x7A,
		VK_F12 = 0x7B,
		VK_F13 = 0x7C,
		VK_F14 = 0x7D,
		VK_F15 = 0x7E,
		VK_F16 = 0x7F,
		VK_F17 = 0x80,
		VK_F18 = 0x81,
		VK_F19 = 0x82,
		VK_F20 = 0x83,
		VK_F21 = 0x84,
		VK_F22 = 0x85,
		VK_F23 = 0x86,
		VK_F24 = 0x87,
		VK_NUMLOCK = 0x90,
		VK_SCROLL = 0x91,
		VK_LSHIFT = 0xA0,
		VK_RSHIFT = 0xA1,
		VK_LCONTROL = 0xA2,
		VK_RCONTROL = 0xA3,
		VK_LMENU = 0xA4,
		VK_RMENU = 0xA5,
		VK_BROWSER_BACK = 0xA6,
		VK_BROWSER_FORWARD = 0xA7,
		VK_BROWSER_REFRESH = 0xA8,
		VK_BROWSER_STOP = 0xA9,
		VK_BROWSER_SEARCH = 0xAA,
		VK_BROWSER_FAVORITES = 0xAB,
		VK_BROWSER_HOME = 0xAC,
		VK_VOLUME_MUTE = 0xAD,
		VK_VOLUME_DOWN = 0xAE,
		VK_VOLUME_UP = 0xAF,
		VK_MEDIA_NEXT_TRACK = 0xB0,
		VK_MEDIA_PREV_TRACK = 0xB1,
		VK_MEDIA_STOP = 0xB2,
		VK_MEDIA_PLAY_PAUSE = 0xB3,
		VK_LAUNCH_MAIL = 0xB4,
		VK_LAUNCH_MEDIA_SELECT = 0xB5,
		VK_LAUNCH_APP1 = 0xB6,
		VK_LAUNCH_APP2 = 0xB7,
		VK_OEM_1 = 0xBA,
		VK_OEM_PLUS = 0xBB,
		VK_OEM_COMMA = 0xBC,
		VK_OEM_MINUS = 0xBD,
		VK_OEM_PERIOD = 0xBE,
		VK_OEM_2 = 0xBF,
		VK_OEM_3 = 0xC0,
		VK_GAMEPAD_A = 0xC3,
		VK_GAMEPAD_B = 0xC4,
		VK_GAMEPAD_X = 0xC5,
		VK_GAMEPAD_Y = 0xC6,
		VK_GAMEPAD_RIGHT_SHOULDER = 0xC7,
		VK_GAMEPAD_LEFT_SHOULDER = 0xC8,
		VK_GAMEPAD_LEFT_TRIGGER = 0xC9,
		VK_GAMEPAD_RIGHT_TRIGGER = 0xCA,
		VK_GAMEPAD_DPAD_UP = 0xCB,
		VK_GAMEPAD_DPAD_DOWN = 0xCC,
		VK_GAMEPAD_DPAD_LEFT = 0xCD,
		VK_GAMEPAD_DPAD_RIGHT = 0xCE,
		VK_GAMEPAD_MENU = 0xCF,
		VK_GAMEPAD_VIEW = 0xD0,
		VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON = 0xD1,
		VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON = 0xD2,
		VK_GAMEPAD_LEFT_THUMBSTICK_UP = 0xD3,
		VK_GAMEPAD_LEFT_THUMBSTICK_DOWN = 0xD4,
		VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT = 0xD5,
		VK_GAMEPAD_LEFT_THUMBSTICK_LEFT = 0xD6,
		VK_GAMEPAD_RIGHT_THUMBSTICK_UP = 0xD7,
		VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN = 0xD8,
		VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT = 0xD9,
		VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT = 0xDA,
		VK_OEM_4 = 0xDB,
		VK_OEM_5 = 0xDC,
		VK_OEM_6 = 0xDD,
		VK_OEM_7 = 0xDE,
		VK_OEM_8 = 0xDF,
		VK_OEM_102 = 0xE2,
		VK_PROCESSKEY = 0xE5,
		VK_PACKET = 0xE7,
		VK_ATTN = 0xF6,
		VK_CRSEL = 0xF7,
		VK_EXSEL = 0xF8,
		VK_EREOF = 0xF9,
		VK_PLAY = 0xFA,
		VK_ZOOM = 0xFB,
		VK_NONAME = 0xFC,
		VK_PA1 = 0xFD,
		VK_OEM_CLEAR = 0xFE
	};
};

} // namespace godot

VARIANT_ENUM_CAST(godot::MoonlightInput::MouseButton);
VARIANT_ENUM_CAST(godot::MoonlightInput::MouseButtonAction);
VARIANT_ENUM_CAST(godot::MoonlightInput::KeyboardAction);
VARIANT_ENUM_CAST(godot::MoonlightInput::KeyboardModifier);
VARIANT_ENUM_CAST(godot::MoonlightInput::TouchEventType);
VARIANT_ENUM_CAST(godot::MoonlightInput::PenToolType);
VARIANT_ENUM_CAST(godot::MoonlightInput::PenButton);
VARIANT_ENUM_CAST(godot::MoonlightInput::ControllerButton);
VARIANT_ENUM_CAST(godot::MoonlightInput::ControllerType);
VARIANT_ENUM_CAST(godot::MoonlightInput::ControllerCapability);
VARIANT_ENUM_CAST(godot::MoonlightInput::MotionType);
VARIANT_ENUM_CAST(godot::MoonlightInput::BatteryState);
VARIANT_ENUM_CAST(godot::MoonlightInput::InputSpecialConstant);
VARIANT_ENUM_CAST(godot::MoonlightInput::VirtualKey);
